#!/usr/bin/env python3
"""
Validate the FFmpeg commands generated by both Sonnet and FastTrack
Test syntax and logical correctness without actually processing video
"""

import subprocess
import tempfile
from pathlib import Path

def test_ffmpeg_syntax(command_name, command):
    """Test FFmpeg command syntax without actually processing"""
    print(f"\n🧪 Testing {command_name}...")
    
    # Create a simple test command that validates syntax
    # Replace input files with lavfi test sources for validation
    test_cmd = command.replace("input_video.mp4", "testsrc2=duration=1:size=320x240:rate=25")
    test_cmd = test_cmd.replace("ambient_audio.mp3", "sine=frequency=440:duration=1")
    test_cmd = test_cmd.replace("audio_track.mp3", "sine=frequency=440:duration=1")
    
    # Replace -i with -f lavfi -i for test sources
    test_cmd = test_cmd.replace("-i testsrc2", "-f lavfi -i testsrc2")
    test_cmd = test_cmd.replace("-i sine", "-f lavfi -i sine")
    
    # Use null output for syntax testing
    test_cmd = test_cmd.replace("vintage_dreamy_30s_final.mp4", "-f null -")
    test_cmd = test_cmd.replace("output_vintage_dreamy.mp4", "-f null -")
    test_cmd = test_cmd.replace("vintage_segment.mp4", "-f null -")
    
    # Limit duration for quick test
    if "-t 30" not in test_cmd:
        test_cmd += " -t 1"
    else:
        test_cmd = test_cmd.replace("-t 30", "-t 1")
    
    print(f"   Command preview: {test_cmd[:100]}...")
    
    try:
        # Test syntax by running with dry-run simulation
        result = subprocess.run(
            test_cmd.split(), 
            capture_output=True, 
            text=True, 
            timeout=10
        )
        
        if result.returncode == 0:
            print(f"   ✅ {command_name}: Syntax VALID")
            return True
        else:
            print(f"   ❌ {command_name}: Syntax ERROR")
            print(f"      Error: {result.stderr[:200]}")
            return False
            
    except subprocess.TimeoutExpired:
        print(f"   ⏰ {command_name}: Timeout (likely working but slow)")
        return True
    except Exception as e:
        print(f"   💥 {command_name}: Exception - {e}")
        return False

def validate_command_logic(command_name, command):
    """Validate logical aspects of the command"""
    print(f"\n🔍 Analyzing {command_name} logic...")
    
    issues = []
    
    # Check for basic requirements
    if "1920x1080" not in command and "1920:1080" not in command:
        issues.append("Missing 1920x1080 resolution specification")
    
    if "25" not in command:
        issues.append("Missing 25fps specification")
    
    if "libx264" not in command:
        issues.append("Missing H.264 codec")
    
    if "aac" not in command:
        issues.append("Missing AAC audio codec")
    
    # Check for vintage effects
    if "colorchannelmixer" not in command:
        issues.append("Missing vintage color grading (colorchannelmixer)")
    
    if "noise" not in command:
        issues.append("Missing film grain (noise filter)")
    
    if "vignette" not in command:
        issues.append("Missing vignette effect")
    
    # Check for dreamy effects
    if "gblur" not in command or "blur" not in command:
        issues.append("Missing blur effects")
    
    if "fade" not in command:
        issues.append("Missing fade effects")
    
    # Check for crossfade
    if "xfade" not in command:
        issues.append("Missing crossfade transition")
    
    # Check audio processing
    if "volume" not in command:
        issues.append("Missing volume adjustment")
    
    if "afade" not in command:
        issues.append("Missing audio fade in/out")
    
    if issues:
        print(f"   ⚠️  Logic issues found:")
        for issue in issues:
            print(f"      • {issue}")
        return False
    else:
        print(f"   ✅ Logic validation PASSED")
        return True

def main():
    print("🎬 FFmpeg Command Validation Test")
    print("=" * 50)
    
    # Sonnet multi-step commands
    sonnet_commands = {
        "Sonnet Step 1 (Vintage)": '''ffmpeg -y -f lavfi -i testsrc2=duration=15:size=1920x1080:rate=25 -vf "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,hue=s=0.6,noise=alls=20:allf=t,vignette=PI/6" -c:v libx264 -preset medium -crf 23 -r 25 -s 1920x1080 -an -f null -''',
        
        "Sonnet Step 2 (Dreamy)": '''ffmpeg -y -f lavfi -i testsrc2=duration=15:size=1920x1080:rate=25 -vf "gblur=sigma=3:steps=1,eq=brightness=0.1:contrast=0.9,boxblur=luma_radius=1:luma_power=0.5,fade=t=out:st=13:d=2" -c:v libx264 -preset medium -crf 23 -r 25 -s 1920x1080 -an -f null -''',
        
        "Sonnet Complete": '''ffmpeg -y -f lavfi -i testsrc2=duration=30:size=1920x1080:rate=25 -f lavfi -i sine=frequency=440:duration=30 -filter_complex "[0:v]split=2[v1][v2]; [v1]trim=0:15,setpts=PTS-STARTPTS,colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,hue=s=0.6,noise=alls=20:allf=t,vignette=PI/6[vintage]; [v2]trim=15:30,setpts=PTS-STARTPTS,gblur=sigma=3:steps=1,eq=brightness=0.1:contrast=0.9,boxblur=luma_radius=1:luma_power=0.5,fade=t=out:st=13:d=2[dreamy]; [vintage][dreamy]xfade=transition=fade:duration=2:offset=13[video]; [1:a]volume=0.7,afade=t=in:st=0:d=1,afade=t=out:st=28.5:d=1.5[audio]" -map "[video]" -map "[audio]" -c:v libx264 -preset medium -crf 23 -c:a aac -b:a 128k -ar 44100 -r 25 -s 1920x1080 -t 1 -f null -'''
    }
    
    # FastTrack single command
    fasttrack_command = '''ffmpeg -f lavfi -i testsrc2=duration=30:size=1920x1080:rate=25 -f lavfi -i sine=frequency=440:duration=30 -filter_complex "[0:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:-1:-1:black,fps=25[scaled]; [scaled]split=2[v1][v2]; [v1]trim=start=0:duration=15,colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131:0:0:0:0:1,curves=all='0/0.05 0.5/0.45 1/0.95',noise=alls=20:allf=t+u,vignette=angle=PI/4:mode=forward:eval=frame[vintage]; [v2]trim=start=15:duration=15,gblur=sigma=3:steps=1,eq=brightness=0.1:saturation=0.8,gblur=sigma=1.5:steps=1[dreamy_base]; [dreamy_base]fade=t=out:st=13:d=2:color=black[dreamy]; [vintage][dreamy]xfade=transition=fade:duration=2:offset=13[video_out]; [1:a]volume=0.7,afade=t=in:st=0:d=1,afade=t=out:st=28.5:d=1.5[audio_out]" -map "[video_out]" -map "[audio_out]" -c:v libx264 -preset medium -crf 23 -c:a aac -ar 44100 -b:a 128k -t 1 -f null -'''
    
    # Test all commands
    results = {}
    
    # Test Sonnet commands
    for name, cmd in sonnet_commands.items():
        syntax_valid = test_ffmpeg_syntax(name, cmd)
        logic_valid = validate_command_logic(name, cmd)
        results[name] = {"syntax": syntax_valid, "logic": logic_valid}
    
    # Test FastTrack command
    fasttrack_syntax = test_ffmpeg_syntax("FastTrack Complete", fasttrack_command)
    fasttrack_logic = validate_command_logic("FastTrack Complete", fasttrack_command)
    results["FastTrack Complete"] = {"syntax": fasttrack_syntax, "logic": fasttrack_logic}
    
    # Summary
    print(f"\n📊 VALIDATION SUMMARY")
    print("=" * 50)
    
    for name, result in results.items():
        syntax_status = "✅" if result["syntax"] else "❌"
        logic_status = "✅" if result["logic"] else "⚠️"
        print(f"{syntax_status} {logic_status} {name}")
    
    total_commands = len(results)
    syntax_passed = sum(1 for r in results.values() if r["syntax"])
    logic_passed = sum(1 for r in results.values() if r["logic"])
    
    print(f"\n🎯 Results:")
    print(f"   Syntax validation: {syntax_passed}/{total_commands} passed")
    print(f"   Logic validation: {logic_passed}/{total_commands} passed")
    
    if syntax_passed == total_commands and logic_passed == total_commands:
        print(f"\n🎉 ALL COMMANDS VALIDATED SUCCESSFULLY!")
        print(f"✅ Both Sonnet and FastTrack generated working FFmpeg commands")
        print(f"✅ MD specification → FFmpeg conversion SUCCESSFUL")
    else:
        print(f"\n⚠️  Some commands need refinement")

if __name__ == "__main__":
    main()